# OptiCrop: Smart Agricultural Production Optimization Engine

### Machine Learning Model Development Notebook

This notebook demonstrates the complete machine learning workflow for the OptiCrop project. It covers dataset loading, preprocessing, exploratory data analysis, model training, evaluation, and saving the best-performing model for deployment in the Flask web application.

## 1. Import Required Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder

from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.cluster import KMeans

import joblib

## 2. Load the Dataset

In [2]:
df = pd.read_csv("../dataset/Crop_recommendation.csv")

df.head()

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

## 3. Exploratory Data Analysis (EDA)

In [3]:
df.info()
df.describe()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   N            2200 non-null   int64
 1   P            2200 non-null   int64
 2   K            2200 non-null   int64
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
 7   label        2200 non-null   object
dtypes: float64(4), int64(3), object(1)
memory usage: 137.6+ KB

(2200, 8)

## 4. Check for Missing Values

In [4]:
df.isnull().sum()

N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(0)

## 5. Data Preprocessing

In [6]:
X = df.drop("label", axis=1)
y = df["label"]

X.head()

    N   P   K  temperature   humidity        ph    rainfall
0  90  42  43    20.879744  82.002744  6.502985  202.935536
1  85  58  41    21.770462  80.319644  7.038096  226.655537
2  60  55  44    23.004459  82.320763  7.840207  263.964248
3  74  35  40    26.491096  80.158363  6.980401  242.864034
4  78  42  42    20.130175  81.604873  7.628473  262.717340

In [7]:
encoder = LabelEncoder()

y = encoder.fit_transform(y)

print(encoder.classes_)

['apple' 'banana' 'blackgram' 'chickpea' 'coconut' 'coffee' 'cotton'
 'grapes' 'jute' 'kidneybeans' 'lentil' 'maize' 'mango' 'mothbeans'
 'mungbean' 'muskmelon' 'orange' 'papaya' 'pigeonpeas' 'pomegranate'
 'rice' 'watermelon']

In [8]:
y[:10]

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

## 6. Splitting Data into Training and Testing Sets

In [9]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training samples :", X_train.shape)
print("Testing samples :", X_test.shape)

Training samples : (1760, 7)
Testing samples : (440, 7)

## 7. K-Nearest Neighbors (KNN)

In [10]:
knn = KNeighborsClassifier()

knn.fit(X_train, y_train)

knn_pred = knn.predict(X_test)

knn_accuracy = accuracy_score(y_test, knn_pred)

print("KNN Accuracy :", knn_accuracy)

KNN Accuracy : 0.9704545454545455

## 8. Logistic Regression

In [11]:
lr = LogisticRegression(max_iter=1000)

lr.fit(X_train, y_train)

lr_pred = lr.predict(X_test)

lr_accuracy = accuracy_score(y_test, lr_pred)

print("Logistic Regression Accuracy :", lr_accuracy)

Logistic Regression Accuracy : 0.9522727272727273

c:\Users\dimpl\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:470: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

## 9. Decision Tree

In [12]:
dt = DecisionTreeClassifier(random_state=42)

dt.fit(X_train, y_train)

dt_pred = dt.predict(X_test)

dt_accuracy = accuracy_score(y_test, dt_pred)

print("Decision Tree Accuracy :", dt_accuracy)

Decision Tree Accuracy : 0.9863636363636363

## 10. Random Forest

In [13]:
rf = RandomForestClassifier(random_state=42)

rf.fit(X_train, y_train)

rf_pred = rf.predict(X_test)

rf_accuracy = accuracy_score(y_test, rf_pred)

print("Random Forest Accuracy :", rf_accuracy)

Random Forest Accuracy : 0.9931818181818182

## 11. K-Means Clustering

In [14]:
kmeans = KMeans(n_clusters=22, random_state=42)

kmeans.fit(X)

print("K-Means model trained successfully.")

K-Means model trained successfully.

## 12. Model Performance Comparison

In [15]:
results = pd.DataFrame({
    "Model": [
        "KNN",
        "Logistic Regression",
        "Decision Tree",
        "Random Forest"
    ],
    "Accuracy": [
        knn_accuracy,
        lr_accuracy,
        dt_accuracy,
        rf_accuracy
    ]
})

results.sort_values(by="Accuracy", ascending=False)

                 Model  Accuracy
3        Random Forest  0.993182
2        Decision Tree  0.986364
0                  KNN  0.970455
1  Logistic Regression  0.952273

## 13. Save the Best Performing Model

In [16]:
joblib.dump(rf, "../model/crop_model.pkl")

joblib.dump(encoder, "../model/label_encoder.pkl")

print("Model and Label Encoder saved successfully.")

Model and Label Encoder saved successfully.

## 14. Test Prediction

In [17]:
sample = np.array([[90, 42, 43, 20, 82, 6.5, 202]])

prediction = rf.predict(sample)

crop = encoder.inverse_transform(prediction)

print("Recommended Crop :", crop[0])

Recommended Crop : rice

c:\Users\dimpl\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

# Conclusion

The OptiCrop machine learning pipeline was successfully developed by preprocessing the agricultural dataset, training multiple machine learning models, and comparing their performance. Among the evaluated models, the Random Forest classifier achieved the highest accuracy and was selected as the final model. The trained model and label encoder were saved using Joblib and integrated with the Flask backend to provide real-time crop recommendations through the OptiCrop web application.